banner:
  location: banner.txt

spring:
  profiles.active: default
  application.name: "tde"

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#    database-platform: org.hibernate.dialect.Oracle10gDialect

server:
  port: 8088


--- # Sai's Dev

spring:
  profiles: SAI

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.129:3306/fangzhengju?useSSL=false
    username: root
    password: Pass1234
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@//192.168.1.110:1521/ORCL
#    username: i1
#    password: i1
  erpDatasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.129:3306/fangzhengju?useSSL=false
      username: root
      password: Pass1234